# Generated by Django 4.2.2 on 2023-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_alter_restaurants_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurants",
            name="items_data",
        ),
        migrations.AddField(
            model_name="restaurants",
            name="items",
            field=models.TextField(default="{}"),
        ),
        migrations.DeleteModel(
            name="ItemsData",
        ),
    ]
