# Generated by Django 4.2.2 on 2023-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_alter_restaurants_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="lat_long",
            field=models.TextField(),
        ),
    ]
