# Generated by Django 4.2.2 on 2023-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0006_alter_restaurants_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="location",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="name",
            field=models.TextField(),
        ),
    ]
