# Generated by Django 4.2.2 on 2023-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0007_alter_restaurants_location_alter_restaurants_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="location",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="name",
            field=models.CharField(max_length=45),
        ),
    ]
