# Generated by Django 4.2.2 on 2023-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0008_alter_restaurants_location_alter_restaurants_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="full_details",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="restaurants",
            name="items",
            field=models.JSONField(),
        ),
    ]
