# Generated by Django 4.2.2 on 2023-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0017_alter_restaurants_full_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="lat_long",
            field=models.CharField(max_length=45),
        ),
    ]
