# Generated by Django 4.2.2 on 2023-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0020_alter_restaurants_lat_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="lat_long",
            field=models.TextField(max_length=45),
        ),
    ]
